# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_search.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13vector_search.proto\x12\x0fvectorsearch.v1\"\xa5\x01\n\rSearchRequest\x12\x17\n\x0fquery_embedding\x18\x01 \x03(\x02\x12\r\n\x05top_n\x18\x02 \x01(\x05\x12<\n\x07\x66ilters\x18\x03 \x03(\x0b\x32+.vectorsearch.v1.SearchRequest.FiltersEntry\x1a.\n\x0c\x46iltersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"C\n\x0cSearchResult\x12\x10\n\x08\x63hunk_id\x18\x01 \x01(\t\x12\x0e\n\x06\x64oc_id\x18\x02 \x01(\t\x12\x11\n\tvec_score\x18\x03 \x01(\x02\"W\n\x0eSearchResponse\x12.\n\x07results\x18\x01 \x03(\x0b\x32\x1d.vectorsearch.v1.SearchResult\x12\x15\n\rindex_version\x18\x02 \x01(\t\"\x0f\n\rHealthRequest\">\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x1c\n\x14loaded_index_version\x18\x02 \x01(\t2\xab\x01\n\x13VectorSearchService\x12I\n\x06Search\x12\x1e.vectorsearch.v1.SearchRequest\x1a\x1f.vectorsearch.v1.SearchResponse\x12I\n\x06Health\x12\x1e.vectorsearch.v1.HealthRequest\x1a\x1f.vectorsearch.v1.HealthResponseB!Z\x1fsearchrank/proto/vectorsearchv1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_search_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\037searchrank/proto/vectorsearchv1'
  _SEARCHREQUEST_FILTERSENTRY._options = None
  _SEARCHREQUEST_FILTERSENTRY._serialized_options = b'8\001'
  _SEARCHREQUEST._serialized_start=41
  _SEARCHREQUEST._serialized_end=206
  _SEARCHREQUEST_FILTERSENTRY._serialized_start=160
  _SEARCHREQUEST_FILTERSENTRY._serialized_end=206
  _SEARCHRESULT._serialized_start=208
  _SEARCHRESULT._serialized_end=275
  _SEARCHRESPONSE._serialized_start=277
  _SEARCHRESPONSE._serialized_end=364
  _HEALTHREQUEST._serialized_start=366
  _HEALTHREQUEST._serialized_end=381
  _HEALTHRESPONSE._serialized_start=383
  _HEALTHRESPONSE._serialized_end=445
  _VECTORSEARCHSERVICE._serialized_start=448
  _VECTORSEARCHSERVICE._serialized_end=619
# @@protoc_insertion_point(module_scope)
